# Generated by Django 5.0.3 on 2024-04-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='dataBase',
            field=models.CharField(default='Simple Scan', max_length=15),
            preserve_default=False,
        ),
    ]
