# Generated by Django 5.0.3 on 2024-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0006_remove_scan_database_remove_scan_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.PositiveIntegerField()),
                ('typeScan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScanVulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.PositiveIntegerField()),
                ('DataBase', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='target',
            name='id',
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='target_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
