# Generated by Django 5.0.3 on 2024-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0007_scanports_scanvulnerabilities_remove_scan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='scan_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_id',
        ),
        migrations.RemoveField(
            model_name='target',
            name='target_id',
        ),
        migrations.AddField(
            model_name='scan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
