# Generated by Django 5.0.3 on 2024-05-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0008_remove_scan_scan_id_remove_schedule_schedule_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dateasyn',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
