# Generated by Django 5.0.3 on 2024-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0009_delete_dateasyn_remove_scan_object_id_alter_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='object_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
