# Generated by Django 5.0.3 on 2024-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0010_scan_object_id_alter_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
