# Generated by Django 5.0.3 on 2024-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0012_remove_home_ip_address_scan_remove_home_name_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Configuration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='schedule',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='home',
            name='target',
            field=models.CharField(max_length=30),
        ),
    ]
