# Generated by Django 5.0.3 on 2024-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0014_rename_namevuln_resultvulners_vulnerability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultvulners',
            name='description',
            field=models.TextField(default='PAS DE DESCRIPTIONE'),
            preserve_default=False,
        ),
    ]
