# Generated by Django 5.0.3 on 2024-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0015_resultvulners_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultvulners',
            name='description',
            field=models.CharField(max_length=254),
        ),
    ]
