# Generated by Django 5.0.3 on 2024-05-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0017_alter_resultvulners_vulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultvulners',
            name='description',
            field=models.TextField(),
        ),
    ]
