# Generated by Django 5.0.3 on 2024-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0018_alter_resultvulners_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScriptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nmap Script Type',
                'verbose_name_plural': 'Nmap Script Types',
            },
        ),
        migrations.RemoveField(
            model_name='scan',
            name='object_id',
        ),
    ]
