# Generated by Django 5.0.3 on 2024-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0019_nmapscripttype_remove_scan_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'verbose_name': 'Scan Configuration', 'verbose_name_plural': 'Scan Configurations'},
        ),
        migrations.RemoveField(
            model_name='scan',
            name='scan_type',
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.ManyToManyField(related_name='scans', to='FirstTry.nmapscripttype'),
        ),
    ]
