# Generated by Django 5.0.3 on 2024-05-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0023_remove_customscan_scan_type_customscan_scan_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomScan',
            new_name='CustomScriptType',
        ),
        migrations.RenameField(
            model_name='customscripttype',
            old_name='Scan_Name',
            new_name='Script_Name',
        ),
        migrations.RenameField(
            model_name='customscripttype',
            old_name='scan_type',
            new_name='script_types',
        ),
    ]
