# Generated by Django 5.0.3 on 2024-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstTry', '0024_rename_customscan_customscripttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.FloatField()),
                ('is_exploit', models.BooleanField()),
                ('vulnerability', models.CharField(max_length=50, unique=True)),
                ('Task', models.CharField(max_length=30)),
                ('Host_IP', models.CharField(max_length=30)),
                ('Host_Name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
